### ISSUE TITLE
How to get the original latency using one card?

### ISSUE THREAD

**Issue by Edwardmark** [PipeFusion/PipeFusion#70]
How to get the original latency using one card?
I try to set npus=1 num_patches =1 in benchmark.sh, but it cannot run.

**Comment by Steaunk** [comment]
There are several ways. You can try `torchrun --nproc_per_node=1 scripts/$SCRIPT --model_id $MODEL_ID`

**Comment by Edwardmark** [comment]
> There are several ways. You can try `torchrun --nproc_per_node=1 scripts/$SCRIPT --model_id $MODEL_ID`

torchrun --nproc_per_node=1 ./scripts/pixart_example.py --model_id /data0/ckpts/PixArt-XL-2-1024-MS/ -p pipeline      --height 1024 --width 1024 --no_use_resolution_binning --pp_num_patch 1 --output_file pp_patch_gpu_1_patch_1
(opensora_v1.1) root@gpu4090:/home/d00857890/PipeFusion# torchrun --nproc_per_node=1 ./scripts/pixart_example.py --model_id /data0/ckpts/PixArt-XL-2-1024-MS/ -p pipeline      --height 1024 --width 1024 --no_use_resolution_binning --pp_num_patch 1 --output_file pp_patch_gpu_1_patch_1
/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
WARNING 06-03 14:45:49 [attn.py:32] ring flash attn not found
WARNING 06-03 14:45:49 [attn.py:32] ring flash attn not found
yunchang not found
Some weights of the model checkpoint were not used when initializing Transformer2DModel:
 ['caption_projection.y_embedding']
INFO 06-03 14:45:50 [distri_dit_pip.py:52] Using pipeline parallelism, world_size: 1 and n_device_per_batch: 1
DistriPixArtAlphaPipeline from pretrain stage 1 0.0 GB
Loading pipeline components...:   0%|                                                                                                                        | 0/5 [00:00<?, ?it/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.51it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  4.85it/s]
DistriPixArtAlphaPipeline from pretrain stage 2 13.085676544 GB
  0%|                                                                                                                                                        | 0/6 [00:00<?, ?it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/d00857890/PipeFusion/./scripts/pixart_example.py", line 234, in <module>
[rank0]:     main()
[rank0]:   File "/home/d00857890/PipeFusion/./scripts/pixart_example.py", line 154, in main
[rank0]:     pipeline = DistriPixArtAlphaPipeline.from_pretrained(
[rank0]:   File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/pipefusion-0.0.0b1-py3.10.egg/pipefuser/pipelines/pixartalpha.py", line 100, in from_pretrained
[rank0]:   File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/pipefusion-0.0.0b1-py3.10.egg/pipefuser/pipelines/pixartalpha.py", line 40, in __init__
[rank0]:   File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/pipefusion-0.0.0b1-py3.10.egg/pipefuser/pipelines/pixartalpha.py", line 147, in prepare
[rank0]:   File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/pipefusion-0.0.0b1-py3.10.egg/pipefuser/pipelines/pip/distri_pixartalpha.py", line 361, in __call__
[rank0]:   File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/pipefusion-0.0.0b1-py3.10.egg/pipefuser/utils.py", line 265, in irecv_from_prev
[rank0]:   File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/pipefusion-0.0.0b1-py3.10.egg/pipefuser/utils.py", line 221, in first_recv_from_prev
[rank0]:   File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1929, in recv
[rank0]:     pg.recv([tensor], src, tag).wait()
[rank0]: RuntimeError: NCCL Error 5: invalid usage (run with NCCL_DEBUG=WARN for details)
E0603 14:46:06.517000 139917113861952 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 496465) of binary: /data0/environments/envs/opensora_v1.1/bin/python
Traceback (most recent call last):
  File "/data0/environments/envs/opensora_v1.1/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.3.0', 'console_scripts', 'torchrun')())
  File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data0/environments/envs/opensora_v1.1/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
./scripts/pixart_example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-03_14:46:06
  host      : gpu4090
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 496465)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by Edwardmark** [comment]
> There are several ways. You can try `torchrun --nproc_per_node=1 scripts/$SCRIPT --model_id $MODEL_ID`

Thanks, it works.
