### ISSUE TITLE
RuntimeError for batch size greater than 1 in DistriPixArtAlphaPipeline

### ISSUE THREAD

**Issue by SaudxInu** [PipeFusion/PipeFusion#81]
Hi,

@feifeibear If I change the batch size in `.scripts/pixart_example.py` I am getting the following error. I have created an issue for the same.

```python
distri_config = DistriConfig(
        height=args.height,
        width=args.width,
        warmup_steps=args.pipefusion_warmup_step,
        do_classifier_free_guidance=True,
        split_batch=False,
        parallelism=args.parallelism,
        mode=args.sync_mode,
        pp_num_patch=args.pp_num_patch,
        use_resolution_binning=not args.no_use_resolution_binning,
        use_cuda_graph=args.use_cuda_graph,
        attn_num=args.attn_num,
        scheduler=args.scheduler,
        ulysses_degree=args.ulysses_degree,
        batch_size=2,
    )
...
output = pipeline(
        prompt=["An astronaut riding a green horse", "An astronaut riding a green horse"],
        generator=torch.Generator(device="cuda").manual_seed(42),
        output_type=args.output_type,
        num_inference_steps=args.pipefusion_warmup_step + 1,
    )
```
`[rank0]: RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0`

Also, please cross-check the script for --parallelism=pipefusion.

Please let me know if I am doing something wrong.

Thanks,
Saud

**Comment by SaudxInu** [comment]
If I comment out the following lines (269, 270) in `PipeFusion/pipefuser/pipelines/pixartalpha.py` the script is running fine.

```python
# Pre-run
pipeline.transformer.set_counter(0)
pipeline.transformer(**static_inputs, return_dict=False, record=True)
```

I think there is some bug in static inputs.

After commenting out script is working fine for all parallelism configs except pipefusion.

`RuntimeError: NCCL Error 5: invalid usage (run with NCCL_DEBUG=WARN for details)`

**Comment by Steaunk** [comment]
> If I comment out the following lines (269, 270) in `PipeFusion/pipefuser/pipelines/pixartalpha.py` the script is running fine for number of GPUs 1 and all parallelism except pipefusion.
> 
> ```python
> # Pre-run
> pipeline.transformer.set_counter(0)
> pipeline.transformer(**static_inputs, return_dict=False, record=True)
> ```
> 
> I think there is some bug in static inputs.
> 
> But for GPUs greater than 1 the script again breaks.
> 
> `torchrun --nproc_per_node=2 scripts/pixart_example.py`
> 
> `[rank0]: RuntimeError: The size of tensor a (1152) must match the size of tensor b (2304) at non-singleton dimension 1`

Thanks for your help. I found the problem was that we did not set prompt for batch_size>1.
